const products = [
 {category:'Linen shirt',name:'Relaxed Linen Blend Shirt',brand:'MANGO',rating:'4.5 ★',match:'99% match',image:'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=600&q=85',offers:[['Ajio','₹1,299','₹2,599','50% off'],['Myntra','₹1,499','₹2,499','40% off'],['Amazon India','₹1,399','₹2,499','44% off']]},
 {category:'Slim fit jeans',name:'High Rise Straight Jeans',brand:'LEVI’S',rating:'4.7 ★',match:'97% match',image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=600&q=85',offers:[['Flipkart','₹1,999','₹3,999','50% off'],['Amazon India','₹2,049','₹3,999','49% off'],['Myntra','₹2,199','₹3,999','45% off']]},
 {category:'White sneakers',name:'Court Vision Low Next Nature',brand:'NIKE',rating:'4.8 ★',match:'98% match',image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=85',offers:[['Amazon India','₹4,499','₹5,695','21% off'],['Myntra','₹4,699','₹5,695','18% off'],['Nike India','₹4,995','₹5,695','12% off']]},
 {category:'Gold hoops',name:'Textured Mini Hoop Earrings',brand:'IYANA',rating:'4.4 ★',match:'95% match',image:'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=600&q=85',offers:[['Amazon India','₹699','₹1,199','42% off'],['Nykaa Fashion','₹799','₹1,299','38% off'],['Myntra','₹849','₹1,299','35% off']]}
];
const grid=document.querySelector('#products'),template=document.querySelector('#product-template');let mode='all';
function price(v){return +v.replace(/[^0-9]/g,'')}
function render(){let data=[...products];if(mode==='discount')data=data.filter(p=>p.offers.some(o=>price(o[2])>price(o[1])));if(mode==='fast')data=data.filter((_,i)=>i<3);let sort=document.querySelector('#sort').value;if(sort==='price')data.sort((a,b)=>price(a.offers[0][1])-price(b.offers[0][1]));if(sort==='rating')data.sort((a,b)=>parseFloat(b.rating)-parseFloat(a.rating));grid.innerHTML='';data.forEach(p=>{const n=template.content.cloneNode(true),best=p.offers.reduce((a,b)=>price(a[1])<price(b[1])?a:b);n.querySelector('img').src=p.image;n.querySelector('img').alt=p.name;n.querySelector('.category').textContent=p.category;n.querySelector('h4').textContent=p.name;n.querySelector('.brand').textContent=p.brand;n.querySelector('.rating').textContent=p.rating;n.querySelector('.match').textContent=p.match;n.querySelector('.best-store').textContent=best[0];n.querySelector('.price').textContent=best[1];const list=n.querySelector('.compare-list');p.offers.forEach((o,i)=>{list.insertAdjacentHTML('beforeend',`<div class="offer"><span><b>${o[0]}</b><small> · ${o[3]}</small></span><span><del>${o[2]}</del> <a href="https://www.google.com/search?q=${encodeURIComponent(p.name+' '+o[0])}" target="_blank" rel="noopener">${o[1]} ↗</a></span></div>`)});const heart=n.querySelector('.heart');heart.onclick=()=>{heart.classList.toggle('saved');heart.textContent=heart.classList.contains('saved')?'♥':'♡';document.querySelector('#wish-count').textContent=document.querySelectorAll('.heart.saved').length};const toggle=n.querySelector('.compare-toggle');toggle.onclick=()=>{list.classList.toggle('open');toggle.querySelector('span').textContent=list.classList.contains('open')?'fewer offers':'all offers';toggle.querySelector('i').textContent=list.classList.contains('open')?'⌃':'⌄'};grid.appendChild(n)})}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.active-filter').classList.remove('active-filter');b.classList.add('active-filter');mode=b.dataset.filter;render()});document.querySelector('#sort').onchange=render;document.querySelector('#generate').onclick=()=>{document.querySelector('.look-header h2').textContent='Your fresh AI edit';document.querySelector('.look-note').innerHTML='Re-ranked for your request · <strong>₹6,296 best total</strong>';render()};render();
