import { useMemo, useRef, useState } from 'react'
import { ArrowRight, ChevronLeft, ChevronRight, Heart, Search, ShoppingBag, Sparkles } from 'lucide-react'

const currency = (amount) => `\u20B9${amount.toLocaleString('en-IN')}`

const looks = [
  { id: 'brunch', title: 'Polished Sunday', mood: 'Easy tailoring for a bright afternoon', total: 6296, image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1100&q=85', tags: ['Smart casual', 'Warm weather'], products: [
    { category: 'Shirt', name: 'Relaxed Linen Blend Shirt', brand: 'MANGO', image: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=700&q=85', rating: 4.5, sizes: 'XS - XL', colors: 'White, oat', offers: [{ store: 'Myntra', price: 1499, original: 2499, discount: 40 }, { store: 'Amazon India', price: 1399, original: 2499, discount: 44 }] },
    { category: 'Jeans', name: 'High Rise Straight Jeans', brand: 'LEVI\'S', image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=700&q=85', rating: 4.7, sizes: '26 - 34', colors: 'Mid blue', offers: [{ store: 'Myntra', price: 2199, original: 3999, discount: 45 }, { store: 'Amazon India', price: 2049, original: 3999, discount: 49 }] },
    { category: 'Sneakers', name: 'Court Vision Low Next Nature', brand: 'NIKE', image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=700&q=85', rating: 4.8, sizes: 'UK 3 - 8', colors: 'White', offers: [{ store: 'Myntra', price: 4699, original: 5695, discount: 18 }, { store: 'Amazon India', price: 4499, original: 5695, discount: 21 }] },
  ] },
  { id: 'date', title: 'After-dark ease', mood: 'Soft shine, sharp lines, no overthinking', total: 7425, image: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=1100&q=85', tags: ['Dinner date', 'Elevated'], products: [
    { category: 'Dress', name: 'Satin Cowl Neck Midi Dress', brand: 'VERO MODA', image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=700&q=85', rating: 4.6, sizes: 'XS - XL', colors: 'Black, burgundy', offers: [{ store: 'Myntra', price: 3199, original: 4999, discount: 36 }, { store: 'Amazon India', price: 2999, original: 4999, discount: 40 }] },
    { category: 'Bag', name: 'Mini Shoulder Bag', brand: 'LAVIE', image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=85', rating: 4.4, sizes: 'One size', colors: 'Black', offers: [{ store: 'Myntra', price: 1499, original: 2499, discount: 40 }, { store: 'Amazon India', price: 1299, original: 2499, discount: 48 }] },
    { category: 'Earrings', name: 'Gold Tone Hoop Earrings', brand: 'IYANA', image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=700&q=85', rating: 4.4, sizes: 'One size', colors: 'Gold', offers: [{ store: 'Myntra', price: 849, original: 1299, discount: 35 }, { store: 'Amazon India', price: 699, original: 1199, discount: 42 }] },
  ] },
  { id: 'weekend', title: 'Weekend movement', mood: 'Sporty pieces with a clean, city-ready edge', total: 5747, image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1100&q=85', tags: ['Day out', 'Relaxed'], products: [
    { category: 'T-shirt', name: 'Essential Cotton T-Shirt', brand: 'ADIDAS', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85', rating: 4.5, sizes: 'S - XXL', colors: 'Cream, charcoal', offers: [{ store: 'Myntra', price: 999, original: 1699, discount: 41 }, { store: 'Amazon India', price: 899, original: 1699, discount: 47 }] },
    { category: 'Trousers', name: 'Wide Leg Cargo Trousers', brand: 'H&M', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=85', rating: 4.3, sizes: 'S - XL', colors: 'Khaki', offers: [{ store: 'Myntra', price: 1899, original: 2999, discount: 37 }, { store: 'Amazon India', price: 1799, original: 2999, discount: 40 }] },
    { category: 'Sneakers', name: 'RS-X Casual Sneakers', brand: 'PUMA', image: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&w=700&q=85', rating: 4.7, sizes: 'UK 6 - 11', colors: 'White, grey', offers: [{ store: 'Myntra', price: 3199, original: 5999, discount: 47 }, { store: 'Amazon India', price: 3049, original: 5999, discount: 49 }] },
  ] },
]

function storeLink(product, store) {
  const query = encodeURIComponent(`${product.brand} ${product.name}`)
  return store === 'Myntra' ? `https://www.myntra.com/${query}` : `https://www.amazon.in/s?k=${query}`
}

function ProductCard({ product, saved, onSave }) {
  const best = product.offers.reduce((lowest, offer) => offer.price < lowest.price ? offer : lowest)
  return <article className="min-w-[280px] overflow-hidden rounded-2xl border border-[#e2e5de] bg-white sm:min-w-[315px]">
    <div className="relative h-64 bg-[#e9e6df]"><img className="h-full w-full object-cover" src={product.image} alt={product.name}/><button onClick={onSave} className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-white/90" aria-label={`Save ${product.name}`}><Heart size={18} className={saved ? 'fill-[#e35638] text-[#e35638]' : ''}/></button><span className="absolute bottom-3 left-3 rounded-full bg-[#dce91d] px-2.5 py-1 font-mono text-[10px]">{product.rating} STAR RATED</span></div>
    <div className="p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-[#748077]">{product.category}</p><h3 className="mt-1 text-base font-semibold">{product.name}</h3><p className="mt-1 text-xs text-[#68756e]">{product.brand} · {product.sizes} · {product.colors}</p>
      <div className="mt-4 space-y-2">{product.offers.map(offer => <a className="flex items-center justify-between rounded-xl border border-[#e2e5de] px-3 py-2.5 transition hover:border-[#17251f] hover:bg-[#f7f6f1]" href={storeLink(product, offer.store)} key={offer.store} target="_blank" rel="noreferrer"><span><b className="text-xs">Buy on {offer.store}</b><small className="ml-1 text-[10px] text-[#68756e]">{offer.discount}% off</small></span><span className="text-right"><del className="mr-1 text-[10px] text-[#78847c]">{currency(offer.original)}</del><strong className="text-sm">{currency(offer.price)}</strong><ArrowRight className="ml-1 inline" size={14}/></span></a>)}</div>
      <p className="mt-3 text-xs text-[#68756e]">Best price <b className="text-[#17251f]">{currency(best.price)} at {best.store}</b></p>
    </div>
  </article>
}

export default function App() {
  const [gender, setGender] = useState('Women'), [occasion, setOccasion] = useState('Brunch'), [budget, setBudget] = useState('Under ₹8,000'), [selectedLook, setSelectedLook] = useState(0), [saved, setSaved] = useState([])
  const carousel = useRef(null)
  const activeLook = looks[selectedLook]
  const visibleLooks = useMemo(() => occasion === 'Date night' ? [looks[1], looks[0], looks[2]] : occasion === 'Weekend' ? [looks[2], looks[0], looks[1]] : looks, [occasion])
  const findLooks = () => setSelectedLook(0)
  const toggleSave = (name) => setSaved(items => items.includes(name) ? items.filter(item => item !== name) : [...items, name])
  const move = (amount) => carousel.current?.scrollBy({ left: amount, behavior: 'smooth' })
  return <div className="min-h-screen bg-[#f8f7f2] text-[#17251f]">
    <header className="sticky top-0 z-30 border-b border-[#dfe2d9] bg-[#f8f7f2]/95 backdrop-blur"><div className="mx-auto flex h-[70px] max-w-[1320px] items-center justify-between px-5 sm:px-8"><a href="#top" className="font-serif text-4xl tracking-[-.1em]">loom<span className="text-[#f06f3e]">.</span></a><nav className="hidden gap-8 text-sm text-[#68756e] md:flex"><a className="font-semibold text-[#17251f]" href="#discover">Discover</a><a href="#looks">Looks</a><a href="#saved">Saved ({saved.length})</a></nav><button className="grid h-10 w-10 place-items-center rounded-full border border-[#dfe2d9]" aria-label="Search"><Search size={18}/></button></div>
      <div className="border-t border-[#e7e8e2] bg-white"><div className="mx-auto flex max-w-[1320px] flex-wrap items-center gap-2 px-5 py-3 sm:px-8"><span className="mr-1 font-mono text-[10px] uppercase tracking-wider text-[#748077]">Find my look</span><select value={gender} onChange={e => setGender(e.target.value)} className="rounded-full border border-[#dfe2d9] bg-[#f8f7f2] px-3 py-2 text-sm outline-none"><option>Women</option><option>Men</option><option>Unisex</option></select><select value={occasion} onChange={e => setOccasion(e.target.value)} className="rounded-full border border-[#dfe2d9] bg-[#f8f7f2] px-3 py-2 text-sm outline-none"><option>Brunch</option><option>Date night</option><option>Weekend</option><option>Work</option><option>Wedding guest</option></select><select value={budget} onChange={e => setBudget(e.target.value)} className="rounded-full border border-[#dfe2d9] bg-[#f8f7f2] px-3 py-2 text-sm outline-none"><option>Under ₹3,000</option><option>Under ₹5,000</option><option>Under ₹8,000</option><option>Under ₹15,000</option></select><button onClick={findLooks} className="ml-auto flex items-center gap-2 rounded-full bg-[#17251f] px-4 py-2.5 text-sm font-semibold text-white"><Sparkles size={16}/> Find looks</button></div></div>
    </header>
    <main id="top" className="mx-auto max-w-[1320px] px-5 sm:px-8"><section id="discover" className="grid gap-7 py-12 lg:grid-cols-[1.1fr_.9fr] lg:py-16"><div className="flex flex-col justify-center"><p className="font-mono text-[11px] uppercase tracking-[.12em] text-[#748077]">AI fashion discovery · India</p><h1 className="mt-4 max-w-2xl text-5xl font-semibold leading-[.94] tracking-[-.065em] sm:text-7xl">Better outfits.<br/><em className="font-serif font-medium">Smarter buying.</em></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-[#68756e]">Personalised looks for {gender.toLowerCase()} shopping, matched to your {occasion.toLowerCase()} plans and {budget.toLowerCase()} budget. Compare trusted retailers, then buy directly from them.</p><div className="mt-7 flex items-center gap-3"><button onClick={() => document.querySelector('#looks')?.scrollIntoView({ behavior: 'smooth' })} className="rounded-full bg-[#dce91d] px-5 py-3 text-sm font-semibold">Explore 3 looks <ArrowRight className="ml-1 inline" size={16}/></button><span className="text-xs text-[#68756e]">No checkout. No markup.</span></div></div><div className="relative min-h-[330px] overflow-hidden rounded-3xl bg-[#e9ddca]"><img className="h-full w-full object-cover" src={activeLook.image} alt={activeLook.title}/><div className="absolute inset-x-5 bottom-5 rounded-2xl bg-white/95 p-4 backdrop-blur"><p className="font-mono text-[10px] uppercase tracking-wider text-[#748077]">Recommended today</p><div className="mt-1 flex items-end justify-between"><div><h2 className="text-2xl font-semibold">{activeLook.title}</h2><p className="mt-1 text-xs text-[#68756e]">{activeLook.mood}</p></div><strong className="text-sm">from {currency(activeLook.total)}</strong></div></div></div></section>
      <section id="looks" className="border-t border-[#dfe2d9] py-10"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.12em] text-[#748077]">Choose a direction</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.05em]">Three looks, curated for you</h2></div><div className="hidden gap-2 sm:flex"><button onClick={() => move(-350)} className="grid h-10 w-10 place-items-center rounded-full border border-[#dfe2d9]" aria-label="Previous looks"><ChevronLeft size={20}/></button><button onClick={() => move(350)} className="grid h-10 w-10 place-items-center rounded-full bg-[#17251f] text-white" aria-label="Next looks"><ChevronRight size={20}/></button></div></div>
        <div ref={carousel} className="mt-6 flex snap-x gap-4 overflow-x-auto pb-3 [scrollbar-width:none]">{visibleLooks.map(look => <button onClick={() => setSelectedLook(looks.findIndex(item => item.id === look.id))} key={look.id} className={`group relative h-[310px] min-w-[84%] snap-start overflow-hidden rounded-2xl text-left sm:min-w-[380px] ${activeLook.id === look.id ? 'ring-2 ring-[#17251f]' : ''}`}><img className="h-full w-full object-cover transition duration-500 group-hover:scale-105" src={look.image} alt={look.title}/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent px-5 pb-5 pt-20 text-white"><div className="flex gap-2">{look.tags.map(tag => <span className="rounded-full bg-white/20 px-2 py-1 font-mono text-[10px]" key={tag}>{tag}</span>)}</div><div className="mt-3 flex items-end justify-between"><div><h3 className="text-2xl font-semibold">{look.title}</h3><p className="mt-1 text-xs text-white/75">{look.mood}</p></div><span className="text-sm font-semibold">{currency(look.total)}</span></div></div></button>)}</div></section>
      <section className="border-t border-[#dfe2d9] py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.12em] text-[#748077]">Shop this look</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{activeLook.title}</h2><p className="mt-2 text-sm text-[#68756e]">{activeLook.products.length} pieces · compare Myntra and Amazon India</p></div><div className="flex items-center gap-2 rounded-full bg-[#e9f0e9] px-3 py-2 text-xs text-[#456b5b]"><ShoppingBag size={15}/> Click any retailer to buy on their site</div></div>
        <div id="saved" className="mt-6 flex gap-4 overflow-x-auto pb-6">{activeLook.products.map(product => <ProductCard key={product.name} product={product} saved={saved.includes(product.name)} onSave={() => toggleSave(product.name)}/>)}</div></section>
      <aside className="mb-10 rounded-2xl border border-[#dfe2d9] bg-white p-5 text-sm text-[#68756e]"><b className="text-[#17251f]">About prices and links:</b> product cards are demo catalogue data. Connect approved Myntra and Amazon affiliate/product-feed APIs to replace it with live product pages, prices, inventory, and images. Never place affiliate API credentials in the browser.</aside>
    </main><footer className="bg-[#17251f] px-5 py-7 text-center font-mono text-[10px] tracking-wider text-[#bfc9be]">LOOM IS A FASHION DISCOVERY PLATFORM. WE HELP YOU FIND PRODUCTS; RETAILERS HANDLE THE PURCHASE.</footer>
  </div>
}
